---
title: "group_project"
author: "Stephanie Pusker"
date: "2022-11-16"
output: 
  flexdashboard::flex_dashboard:
     storyboard: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r, include = FALSE}
library(flexdashboard)
library(readr)
library(lubridate)
library(shiny)
library(jsonlite)
library(maptools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(purrr)
library(leaflet)
library(plotly)
library(DT)
library(ggthemes)
library(viridis)
library(tidyverse)
library(tigris)
library(igraph)
library(visNetwork)
library(gganimate)
library(vcd)
library(remotes)
library(ggiraph)
library(patchwork)

nyc_squirrels <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-29/nyc_squirrels.csv")

nyc_squirrels_clean <- nyc_squirrels %>% 
  select(long, lat, unique_squirrel_id, hectare, date, hectare_squirrel_number,
         age, primary_fur_color, highlight_fur_color, running, chasing,
         climbing, eating, foraging, kuks, quaas, moans, tail_flags,
         tail_twitches, indifferent, runs_from, community_districts,
         police_precincts) %>% 
  mutate(date = mdy(date)) %>% 
  na.omit()

```


### Interactive Map

```{r, map with tigris}

# leaflet map for central park
fur_color <- colorFactor(c("Black","Brown","Gray"),
                               domain = nyc_squirrels_clean$primary_fur_color)

 leaflet() %>% 
  addTiles() %>% 
  fitBounds(-73.9823592,40.7636484,-73.9492441, 40.8005539)%>%
  addTiles() %>% 
  addCircleMarkers(nyc_squirrels_clean$long, 
                   nyc_squirrels_clean$lat, 
                   color = fur_color(nyc_squirrels_clean$primary_fur_color), 
                   radius = 0.5, 
                   fill = T,
                   fillOpacity = 0.2,
                   opacity = 0.6,
                   popup = nyc_squirrels_clean$primary_fur_color)

  

 
```


### Table 

```{r, table}

## Table 1

activity_percentages <- nyc_squirrels_clean %>% 
  select(running, chasing,climbing, eating, foraging, kuks, quaas, moans, tail_flags, tail_twitches, indifferent, runs_from) %>% 
  rownames_to_column(var = "ID") %>% 
  as.data.frame() %>% 
  pivot_longer(cols = running:runs_from, names_to = "activity",
               values_to = "true_false") %>% 
  group_by(activity) %>% 
  nest() %>% 
  mutate(proportion = map(data, ~ .x %>% 
                            pull("true_false") %>% 
                            mean())) %>% 
  unnest(proportion) %>% 
  mutate(percentage = 100*proportion) %>% 
  select(activity, percentage) %>% 
  mutate(activity = gsub("_", " ", activity),
         activity =  str_to_title(activity),
         percentage = round(percentage, 2),
         tooltip_text = paste0(toupper(activity), "\n", 
                   percentage, "%"))
  
```

### Plot

```{r, plot}
activity_graph <- activity_percentages %>% 
ggplot(aes(x = percentage, 
           y = reorder(activity, percentage), 
           fill = activity,
           tooltip = tooltip_text, data_id = activity #<<
           )) +
  geom_col_interactive(color = "black", size = 0.5) +
  labs(x = "Percentage", y = "Activity", title = "Activity Percentages") +
  theme_few() 

girafe(ggobj = activity_graph, width_svg = 5, height_svg = 4)

```
## HTML Trial
```{r}
my_widget <- girafe(ggobj = activity_graph, 
                    width_svg = 10, height_svg = 5) %>%
  girafe_options(opts_hover(css = "fill:cyan;"))

htmlwidgets::saveWidget(my_widget, "my_widget_page.html", 
                        selfcontained = TRUE)
```


## Install software

```{r}
remotes::install_github("hrbrmstr/albersusa")
```


### Network

```{r}


```

